# Generated by Django 4.2.1 on 2023-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
