# Generated by Django 4.2.1 on 2023-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_numberplate_car_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='Location',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
