# Generated by Django 4.2.1 on 2023-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_numberplate_record_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=23, null=True)),
                ('plate', models.CharField(max_length=23, null=True)),
            ],
        ),
    ]
