# Generated by Django 3.2.19 on 2023-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_numberplate_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='Control_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
