# Generated by Django 3.2.19 on 2023-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_numberplate_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='Record_date',
            field=models.DateTimeField(),
        ),
    ]
