# Generated by Django 3.2.19 on 2023-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_numberplate_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='Record_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
