# Generated by Django 3.2.19 on 2023-07-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20230706_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Failled',
        ),
    ]
