# Generated by Django 4.2 on 2023-05-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('car_image', models.ImageField(upload_to='speed_violations/')),
                ('speed_limit', models.IntegerField()),
                ('car_speed', models.IntegerField()),
                ('exceed_speed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedViolationFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fine Amount')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('speed_violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Custome.speedviolation')),
            ],
            options={
                'verbose_name_plural': 'Speed Violation Fines',
            },
        ),
    ]
