# Generated by Django 4.2 on 2023-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custome', '0002_speedviolationfine_dept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolationfine',
            name='dept_status',
            field=models.CharField(choices=[(0, 'Unpai'), (1, 'Paid')], default=0, max_length=20),
        ),
    ]
