# Generated by Django 4.2 on 2023-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custome', '0004_alter_speedviolationfine_dept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolationfine',
            name='dept_status',
            field=models.BooleanField(default=False),
        ),
    ]
