# Generated by Django 4.2 on 2023-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custome', '0005_alter_speedviolationfine_dept_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speedviolationfine',
            old_name='dept_status',
            new_name='paid',
        ),
    ]
