# Generated by Django 4.2.1 on 2023-05-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Custome", "0007_speedviolation_record_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedviolationfine",
            name="speed_violation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Custome.speedviolation"
            ),
        ),
    ]
