# Generated by Django 4.2.1 on 2023-05-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Custome", "0009_alter_speedviolationfine_speed_violation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="FilteredViolation",),
    ]
