# Generated by Django 4.2.1 on 2023-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Custome", "0010_delete_filteredviolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="speedviolation",
            name="fine_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Fine Amount"
            ),
        ),
        migrations.AddField(
            model_name="speedviolation",
            name="location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="speedviolation",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="SpeedViolationFine",),
    ]
