# Generated by Django 4.2.1 on 2023-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Custome", "0011_speedviolation_fine_amount_speedviolation_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedviolation", name="status", field=models.BooleanField(),
        ),
    ]
