# Generated by Django 4.2.1 on 2023-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custome', '0013_alter_speedviolation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolation',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=30),
        ),
    ]
